CREATE TABLE IF NOT EXISTS LI (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PN TEXT NOT NULL,
    EC TEXT NOT NULL,
    height TEXT NOT NULL,
    leafSize TEXT NOT NULL,
    deficiencies TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PH (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PN TEXT NOT NULL,
    ph TEXT NOT NULL,
    EC TEXT NOT NULL,
    height TEXT NOT NULL,
    leafSize TEXT NOT NULL,
    deficiencies TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CalMag (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PN TEXT NOT NULL,
    CM TEXT NOT NULL,
    EC TEXT NOT NULL,
    height TEXT NOT NULL,
    leafSize TEXT NOT NULL,
    deficiencies TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Control (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PN TEXT NOT NULL,
    EC TEXT NOT NULL,
    height TEXT NOT NULL,
    leafSize TEXT NOT NULL,
    deficiencies TEXT NOT NULL
);